apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
type: Opaque
stringData:
  MONGO_ROOT_PASSWORD: "rootpassword"
  MONGODB_URI: "mongodb://root:rootpassword@mongo:27017/ecommerce?authSource=admin"
  SESSION_SECRET: "change-this-session-secret-before-production"
